In [5]:
import pandas as pd
import pymysql.cursors
import numpy as np
import plotly.express as px 
from datetime import datetime
from datetime import time


conn = pymysql.connect(host='192.168.18.27',
                       user='piuser',
                       password='piuser',
                       database='pi2')

tableName = 'compressor_measurements'

cursor = conn.cursor()
cursor.execute("SELECT moment, voltage, current, power_W, energy_WH, power_factor_measured, power_factor_calc, phase_angle_measured, phase_angle_calc FROM pi2." + tableName)
data = cursor.fetchall()
df = pd.DataFrame(data, columns=['moment', 'voltage', 'current', 'power_W', 'energy_WH', 'power_factor_measured', 'power_factor_calc', 'phase_angle_measured', 'phase_angle_calc'])

In [6]:
df

,moment,voltage,current,power_W,energy_WH,power_factor_measured,power_factor_calc,phase_angle_measured,phase_angle_calc
0,2023-03-31 16:23:54,128.7,0.392,49.9,108.0,0.99,0.989,8.11,8.471
1,2023-03-31 16:24:00,128.9,0.393,50.0,108.0,0.99,0.987,8.11,9.243
2,2023-03-31 16:24:06,128.8,0.392,49.9,109.0,0.99,0.988,8.11,8.765
3,2023-03-31 16:24:12,128.8,0.392,49.9,109.0,0.99,0.988,8.11,8.765
4,2023-03-31 16:24:18,128.7,0.392,49.9,109.0,0.99,0.989,8.11,8.471
...,...,...,...,...,...,...,...,...,...
10585,2023-04-01 12:05:55,128.8,0.392,49.8,443.0,0.99,0.986,8.11,9.480
10586,2023-04-01 12:05:58,128.7,0.391,49.7,443.0,0.99,0.988,8.11,9.016
10587,2023-04-01 12:06:01,128.6,0.391,49.7,443.0,0.99,0.988,8.11,8.730
10588,2023-04-01 12:06:04,128.8,0.392,49.8,444.0,0.99,0.986,8.11,9.480
10589,2023-04-01 12:06:07,128.8,0.391,49.7,444.0,0.99,0.987,8.11,9.292